### ISSUE TITLE
Can't Remove Webs

### ISSUE THREAD

**Issue by lambda-11235** [NPXcoot/nssm#24]
I can't find a way to remove webs launched by a black widow other than fire. This becomes problematic if you're attacked by a wooden structure. I'm not sure if this is by design, is a bug, or I'm missing something.

**Comment by taikedz** [comment]
If I remember well, you can use weapons that deal with "snappy" things like foliage to clear webs. However, regular steel/bronze/etc swords will wear very fast. You need to try one of the NSSM weapons instead... ;-)

**Comment by ssieb** [comment]
That works for the regular webs, but not the thick webs.  I haven't found anything that can break those and for some reason fire isn't working on my server.

**Comment by taikedz** [comment]
Oh yes - thick web can't be cut down like normal ones... Fire is sometimes disabled in server mode to prevent griefing by wildfires - see <https://wiki.minetest.net/Fire> the configuration option

**Comment by ssieb** [comment]
It's my server. :-)  And the server setting is set to enable fire.  I suspect one of the mods I've enabled has done something.  I haven't looked through all of them yet.  Anyway, this is off-topic.
@lambda-11235 assuming you are referring to the thick webs, it's by design.  The only way to get rid of them is with fire.

**Comment by lambda-11235** [comment]
Ah, you need a metal sword, stone won't work. Closing this issue as it's not a bug.
